# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Core
          filename: metrics/light.svg
          config_timezone: Europe/Madrid
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: |
            chore: Update light metrics

            [no ci]

          # Display
          template: classic
          base: header, activity, community
          base_indepth: true
          config_animations: yes

          # Options
          plugin_followup: yes
          plugin_followup_sections: user
